# Proxy API requests to backend
[[redirects]]
  from = "/api/*"
  to = "https://murugan-supermarket-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Proxy uploads to backend
[[redirects]]
  from = "/uploads/*"
  to = "https://murugan-supermarket-backend.onrender.com/uploads/:splat"
  status = 200
  force = true

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200